name: Publish

on: push

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: Build
      run: |
        yarn install --frozen-lockfile
        yarn build:publish
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: dist/file.zip
        extension-id: hogefuga(cgmkidanneklhobdpiflbhekpkhglopd)
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}